#sdk: "D:/develtools/ruby187/lib/ruby/gems/1.8/gems/rhodes-3.3.1"
sdkversion: 3.3.0
name: Sencha Getting Started
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.gettingstarted
  BundleURLScheme: gettingstarted
wp:
  productid: '17551640-3f5e-012f-63b0-24badb983752'
symbian:
  uid: '0xea5b3521'
android:
  version: 2.1

extensions: ["json", "another-extension"]
